version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped

  open-webui:
    image: ghcr.io/marjoleinverp/open-webui-govchat-overlay:latest
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
      - govchat-static:/app/backend/static
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - ENABLE_SIGNUP=false
      - ENABLE_LOGIN_FORM=false
      - ENABLE_OAUTH_SIGNUP=true
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - AUTH_PROVIDER=azure
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_CLIENT_TENANT_ID=${MICROSOFT_CLIENT_TENANT_ID}
      - OAUTH_SCOPES=openid email profile groups
      - ENABLE_OAUTH_GROUP_MANAGEMENT=true
      - OAUTH_GROUP_CLAIM=groups
      - ENABLE_OAUTH_GROUP_CREATION=true
      - DEFAULT_LOCALE=nl
      - DATABASE_URL=${DATABASE_URL_OpenWebUI}
      - ENABLE_FORWARD_USER_INFO_HEADERS=true
      - VECTOR_DB=qdrant
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_URI=http://qdrant:6333
      - CORS_ALLOW_ORIGIN=https://jip.meierijstad.nl
      - GLOBAL_LOG_LEVEL=WARNING
      - USER_AGENT=openwebui
      - JWT_EXPIRES_IN=3600
      - STATIC_DIR=/app/backend/static
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  govchat-admin:
    image: ghcr.io/marjoleinverp/open-webui-govchat-overlay-admin:latest
    container_name: govchat-admin
    ports:
      - "3002:3002"
    environment:
      - ADMIN_PASSWORD=${GOVCHAT_ADMIN_PASSWORD}
    volumes:
      - govchat-admin-data:/data
      - govchat-static:/publish
    depends_on:
      - open-webui
    restart: unless-stopped

  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - "9998:9998"
    restart: unless-stopped

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_API_BASE=${AZURE_API_BASE}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
      - LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
      - UI_USERNAME=${UI_USERNAME}
      - UI_PASSWORD=${UI_PASSWORD}
      - DATABASE_URL=${DATABASE_URL_LiteLLM}
    volumes:
      - /opt/litellm/config.yaml:/app/config.yaml:ro
    command: --config /app/config.yaml --detailed_debug

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  ollama: {}
  open-webui: {}
  pgdata: {}
  qdrant_storage: {}
  govchat-admin-data: {}
  govchat-static: {}
